### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by daianaboia** [lit26/Stock_Screener#2]
I can't see anything after running: python3  manage.py runserver

**Comment by lit26** [comment]
Have you installed the frontend packages?

**Comment by daianaboia** [comment]
Yes. with 'pip install -r requirements.txt'. Then 'npm I', and last 'npm run dev'.

That's what I see
<img width="1278" alt="Screenshot 2022-02-11 at 07 12 38" src="https://user-images.githubusercontent.com/82261607/153555725-b7cede20-b383-45fe-9846-b120d9f9fd5b.png">
:

**Comment by lit26** [comment]
I have fixed the frontend. Please update.

**Comment by daianaboia** [comment]
I updated and I repeated the procedure. After npm run dev, that's what I get:
```
> frontend@1.0.0 dev
> webpack --mode development --watch

asset main.js 2.88 MiB [compared for emit] [minimized] (name: main) 1 related asset
orphan modules 3.59 MiB [orphan] 5854 modules
runtime modules 937 bytes 4 modules
cacheable modules 2.47 MiB
  modules by path ./node_modules/ 2.36 MiB 196 modules
  modules by path ./src/ 114 KiB
    modules by path ./src/components/ 110 KiB 40 modules
    modules by path ./src/*.js 1.77 KiB
      ./src/index.js 477 bytes [built] [code generated]
      ./src/App.js 1.31 KiB [built] [code generated]
    modules by path ./src/redux/*.js 717 bytes
      ./src/redux/reducers.js 506 bytes [built] [code generated]
      ./src/redux/action.js 211 bytes [built] [code generated]
    modules by path ./src/*.css 1.7 KiB
      ./src/App.css 324 bytes [built] [code generated]
      ./node_modules/css-loader/dist/cjs.js!./src/App.css 1.38 KiB [built] [code generated]
webpack 5.36.2 compiled successfully in 11147 ms
```
So I opened another terminal and run "python3 manage.py runserver":
```
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
February 11, 2022 - 09:04:03
Django version 3.2, using settings 'Stock_Screener.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[11/Feb/2022 09:04:05] "GET / HTTP/1.1" 200 923

```
and the result is still the old one:
![image](https://user-images.githubusercontent.com/82261607/153564208-4d4dfe01-0239-423d-8029-3e9913931f8c.png)

Am I doing something wrong?

Thank you very much for the assistance :)

**Comment by lit26** [comment]
Maybe your browser is caching. `cmd + shift + R` to reload the page.

**Comment by daianaboia** [comment]
Managed to make it, thanks. Now the problem is that the Graphs are not visible:
![image](https://user-images.githubusercontent.com/82261607/153580067-21455e40-85ee-402d-bc9e-fc0569705c5a.png)

**Comment by lit26** [comment]
I have updated both the frontend and backend. Please check the repo and also upgrade the packages in `requirements.txt`.  Let me know if works.

**Comment by lit26** [comment]
This issue will be closed due to inactivity.

**Comment by daianaboia** [comment]
I'm sorry for the delay in my reply. I just tried again: now I see values on the Watchlist but the Graph is still not appearing.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/82261607/154870689-de83ef83-9ffd-4313-b73a-5bbed770fe75.png">

**Comment by lit26** [comment]
That is weird. Can you check if it is a backend error (check from the terminal) or a frontend error (check from the browser inspect)?

**Comment by daianaboia** [comment]
In the console I get this error: 

_DevTools failed to load source map: Could not load content for chrome-extension://almalgbpmcfpdaopimbdchdliminoign/content/post_api.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME_

Do you think is related to the problem?

Thanks!

**Comment by lit26** [comment]
I don't think so. But you can check if there is 404 status code in the terminal except the `favicon.ico`.

**Comment by lit26** [comment]
Please also check the api with `http://127.0.0.1:8000/api/quote/q=AAPL&t=1d&p=ytd` if it returns correctly.

**Comment by daianaboia** [comment]
In the terminal I see some exceptions:

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/Users/daianaboia/repos/Stock_Screener/env/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)`

**Comment by lit26** [comment]
This is a known issue in `yfinance` package. Please upgrade to yfinance=0.1.63 and check if works.

**Comment by daianaboia** [comment]
Now it works perfectly! Thank you very much for your patience :)

**Comment by lit26** [comment]
You're welcome.
